### ISSUE TITLE
Please allow monetary contributions for this project

### ISSUE THREAD

**Issue by carlosjgp** [mendhak/docker-http-https-echo#25]
I've been hammering my head for a whole day trying to make a 3rd party application written in Erlang to work behind a reverse proxy when everything looked just fine an the application logging was enough at best

This container did help me to understand what this app was expecting to see and how... and oddly how much (it didn't like multiple values on the `X-Forwarded-*` headers) xD 

I'll happily pay for a coffee/beer is you provide a way for doing this ;)
- Paypal
- https://github.com/sponsors

**Comment by mendhak** [comment]
Hey it's really nice to hear stories like yours, because it's motivating to know that the tool is useful!  I'm not familiar with Erlang, but when I looked it up it seems to be behind some well known projects like RabbitMQ, CouchDB, very interesting.

I won't say no to coffee! if you'd like, you can send to my Paypal which is `gpslogger@mendhak.com`

Thanks!
