### ISSUE TITLE
Is it possible to view all env variables present in container

### ISSUE THREAD

**Issue by mk2134226** [mendhak/docker-http-https-echo#43]
It would be good if we can see  all the env variables present inside conatiner

**Comment by mendhak** [comment]
I have added this feature in the PR https://github.com/mendhak/docker-http-https-echo/pull/44/files
Can you test it, I've made a test tag called `:envstuff` 

You'll need to pass an environment variable to see the environment variables :laughing:! 
This is because environment variables could be sensitive so I didn't want to make it a default behavior

```bash
docker run -d --rm -e ECHO_INCLUDE_ENV_VARS=1 --name http-echo-tests -p 8080:8080 -p 8443:8443 -t mendhak/http-https-echo:envstuff
```

**Comment by mendhak** [comment]
Tag `:26` has been published to Docker Hub

https://hub.docker.com/r/mendhak/http-https-echo/tags
